version: '3.7'
services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./.docker/php-fpm
        ports:
            - "9000:9001"
        volumes:
            - .:/var/www/symfony:cached
            - ./.docker/logs/symfony:/var/www/symfony/var/log:cached
        links:
            - db
        extra_hosts:
            - "docker-host.localhost:127.0.0.1"
    nginx:
        build: ./.docker/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
        volumes:
            - ./.docker/logs/nginx:/var/log/nginx:cached
            - .:/var/www/symfony:cached
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./.docker/elk/logstash:/etc/logstash:cached
            - ./.docker/elk/logstash/patterns:/opt/logstash/patterns:cached
            - ./.docker/logs/symfony:/var/www/symfony/var/log:cached
            - ./.docker/logs/nginx:/var/log/nginx:cached

